name = "Graph Generator for Health Data"
packages = ["matplotlib", "seaborn"]
[files]
"https://raw.githubusercontent.com/liam-kelly-024/graph_gui_assets/refs/heads/main/heartrate_dataset.csv" = ""
"https://raw.githubusercontent.com/liam-kelly-024/graph_gui_assets/refs/heads/main/stress_dataset.csv" = ""
"https://raw.githubusercontent.com/liam-kelly-024/graph_gui_assets/refs/heads/main/blood_oxygen_dataset.csv" = ""