name = "Graph Generator for Health Data"
packages = ["matplotlib", "seaborn"]
[files]
"https://raw.githubusercontent.com/liam-kelly-024/lc-project/refs/heads/main/assets/heartrate_dataset.csv" = ""
"https://raw.githubusercontent.com/liam-kelly-024/lc-project/refs/heads/main/assets/stress_dataset.csv" = ""
"https://raw.githubusercontent.com/liam-kelly-024/lc-project/refs/heads/main/assets/blood_oxygen_dataset.csv" = ""
